### ISSUE TITLE
Cleanup repo in preparation for Maesh

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-maesh#1]
Displace Istio references with references to Maesh. Remove Istio specific code.

**Comment by leecalcote** [comment]
Thanks for jumping in here, @alejandrox1! One issue that is now being corrected in the other repos is an outdated link in each of their READMEs to the Contributor Welcome Guide. Here is the link to the new document's location - https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit

**Comment by leecalcote** [comment]
FYI - This repo currently fails to build based on residual ```Meshery adapter for Istio``` code. The [meshery-istio repo](https://github.com/layer5io/meshery-istio) was used as a template for the Maesh repo. 

Here is the build error:

```
The command '/bin/sh -c cd cmd; go build -ldflags="-w -s" -a -o /meshery-istio .' returned a non-zero code: 1
```

**Comment by alejandrox1** [comment]
Thank you for the additional info @leecalcote 
Will work on fixing it!

**Comment by girishranganathan** [comment]
FYI: the Go build & Docker build issues are resolved. You should be good to start and take it from here.
