### ISSUE TITLE
[CI] Add GitHub Action for Slack Notify on Star

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-maesh#38]
Similar to how this is done for other repos.

**Comment by morrme** [comment]
Has this already been done? 

https://github.com/layer5io/meshery-maesh/blob/master/.github/workflows/slack.yml

**Comment by leecalcote** [comment]
Oops. Sorry, @morrme. I forgot to close this one. Yes, it was just completed - https://github.com/layer5io/meshery-maesh/blob/master/.github/workflows/slack.yml
