### ISSUE TITLE
Add Release Drafter for the repository 

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/meshery-maesh#43]
**Current situation**
Each of the layer5 repositories needs releaseDrafter automation as had been done in the meshery project which takes care of drafting release notes.

**Desired Situation**

Add ReleaseDrafter configuration yaml file & GitHub Action.

---
**Additional context**

[ReleaseDrafter Configuration File](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml)
[ReleaseDrafter GitHub Action](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml)

**Comment by leecalcote** [comment]
Excellent

**Comment by jomefavourite** [comment]
I'll like to take this up

**Comment by leecalcote** [comment]
@jomefavourite excellent. Thanks for your constant engagement in the community. You're welcome to self-assign any unassigned issue with the help-wanted label.

**Comment by jomefavourite** [comment]
@leecalcote Okay. I've created a Pull request already. I just hope I get it this time with no issues

**Comment by leecalcote** [comment]
Thanks, @jomefavourite :thum
