### ISSUE TITLE
Add Maesh logo and description section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-maesh#48]
**Current State of the README site**
Maesh has a new logo - https://traefik.io/static/traefik-mesh-logo-1a85e104816d54531d55c520369bddc1.svg

**Desired State of the README**
A new section in the README can be created like that of the readme in https://github.com/layer5io/meshery-osm.  Description of Maesh - https://traefik.io/traefik-mesh/

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by bartkalanski** [comment]
I could get this done by tomorrow

**Comment by leecalcote** [comment]
Thank you, @bartkalanski

**Comment by leecalcote** [comment]
Done. Thank you, @bartkalanski
